Dim fso, folder, file, path
Set fso = CreateObject("Scripting.FileSystemObject")

path = "K:\Oishipan\OishipanMVC\Areas\Admin\Views\Users"

' Create directory if it doesn't exist
If Not fso.FolderExists(path) Then
    fso.CreateFolder(path)
End If

' Create Index.cshtml
Dim indexFile
Set indexFile = fso.CreateTextFile(path & "\Index.cshtml", True, True)
indexFile.WriteLine("@model IEnumerable<OishipanAPI.DTOs.UserDto>")
indexFile.WriteLine("")
indexFile.WriteLine("@{")
indexFile.WriteLine("    ViewData[""Title""] = ""Quản lý người dùng"";")
indexFile.WriteLine("}")
indexFile.WriteLine("")
indexFile.WriteLine("<div class=""container-fluid"">")
indexFile.WriteLine("    <div class=""d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4 gap-3"">")
indexFile.WriteLine("        <div>")
indexFile.WriteLine("            <h4 class=""fw-semibold"">Danh sách người dùng</h4>")
indexFile.WriteLine("            <p class=""text-muted mb-0"">Quản lý thông tin và quyền hạn của người dùng.</p>")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("        <div class=""d-flex gap-2 flex-wrap"">")
indexFile.WriteLine("            <a href=""/admin/users/create"" class=""btn btn-success rounded-pill px-4""><i class=""bi bi-plus-circle me-2""></i>Thêm người dùng</a>")
indexFile.WriteLine("            <a href=""/admin"" class=""btn btn-outline-secondary rounded-pill""><i class=""bi bi-arrow-left me-2""></i>Quay lại</a>")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("    </div>")
indexFile.WriteLine("")
indexFile.WriteLine("    @if (!string.IsNullOrEmpty(ViewBag.Error))")
indexFile.WriteLine("    {")
indexFile.WriteLine("        <div class=""alert alert-danger alert-dismissible fade show"" role=""alert"">")
indexFile.WriteLine("            <i class=""bi bi-exclamation-circle me-2""></i>@ViewBag.Error")
indexFile.WriteLine("            <button type=""button"" class=""btn-close"" data-bs-dismiss=""alert""></button>")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("    }")
indexFile.WriteLine("")
indexFile.WriteLine("    <!-- SEARCH & FILTER -->")
indexFile.WriteLine("    <div class=""card admin-panel-card shadow-sm border-0 rounded-4 p-4 mb-4"">")
indexFile.WriteLine("        <div class=""row g-3"">")
indexFile.WriteLine("            <div class=""col-md-6"">")
indexFile.WriteLine("                <form method=""get"" class=""d-flex gap-2"">")
indexFile.WriteLine("                    <input type=""text"" name=""search"" class=""form-control form-control-dark search-box flex-grow-1""")
indexFile.WriteLine("                           placeholder=""Tìm kiếm theo tên hoặc email..."" value=""@ViewBag.SearchTerm"">")
indexFile.WriteLine("                    <button type=""submit"" class=""btn btn-primary rounded-pill px-4"">")
indexFile.WriteLine("                        <i class=""bi bi-search me-1""></i>Tìm")
indexFile.WriteLine("                    </button>")
indexFile.WriteLine("                </form>")
indexFile.WriteLine("            </div>")
indexFile.WriteLine("            <div class=""col-md-3"">")
indexFile.WriteLine("                <form method=""get"" class=""d-flex gap-2"">")
indexFile.WriteLine("                    <select name=""role"" class=""form-select form-control-dark rounded-pill"">")
indexFile.WriteLine("                        <option value="""">Tất cả Role</option>")
indexFile.WriteLine("                        <option value=""Admin"" @(ViewBag.CurrentRole == ""Admin"" ? ""selected"" : """")>Admin</option>")
indexFile.WriteLine("                        <option value=""Staff"" @(ViewBag.CurrentRole == ""Staff"" ? ""selected"" : """")>Staff</option>")
indexFile.WriteLine("                        <option value=""User"" @(ViewBag.CurrentRole == ""User"" ? ""selected"" : """")>User</option>")
indexFile.WriteLine("                    </select>")
indexFile.WriteLine("                    <button type=""submit"" class=""btn btn-outline-light rounded-pill px-3"">Lọc</button>")
indexFile.WriteLine("                </form>")
indexFile.WriteLine("            </div>")
indexFile.WriteLine("            <div class=""col-md-3"">")
indexFile.WriteLine("                <form method=""get"" class=""d-flex gap-2"">")
indexFile.WriteLine("                    <select name=""status"" class=""form-select form-control-dark rounded-pill"">")
indexFile.WriteLine("                        <option value="""">Tất cả trạng thái</option>")
indexFile.WriteLine("                        <option value=""true"" @(ViewBag.CurrentStatus == true ? ""selected"" : """")>Hoạt động</option>")
indexFile.WriteLine("                        <option value=""false"" @(ViewBag.CurrentStatus == false ? ""selected"" : """")>Bị khóa</option>")
indexFile.WriteLine("                    </select>")
indexFile.WriteLine("                    <button type=""submit"" class=""btn btn-outline-light rounded-pill px-3"">Lọc</button>")
indexFile.WriteLine("                </form>")
indexFile.WriteLine("            </div>")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("    </div>")
indexFile.WriteLine("")
indexFile.WriteLine("    <!-- USERS TABLE -->")
indexFile.WriteLine("    @if (!Model.Any())")
indexFile.WriteLine("    {")
indexFile.WriteLine("        <div class=""alert alert-secondary"">")
indexFile.WriteLine("            <i class=""bi bi-info-circle me-2""></i>Không tìm thấy người dùng nào.")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("    }")
indexFile.WriteLine("    else")
indexFile.WriteLine("    {")
indexFile.WriteLine("        <div class=""card admin-panel-card shadow-sm border-0 rounded-4 p-4 mb-4"">")
indexFile.WriteLine("            <div class=""table-responsive"">")
indexFile.WriteLine("                <table class=""table align-middle table-dark table-admin"">")
indexFile.WriteLine("                    <thead>")
indexFile.WriteLine("                        <tr>")
indexFile.WriteLine("                            <th style=""width: 10%;"">ID</th>")
indexFile.WriteLine("                            <th style=""width: 20%;"">Họ và tên</th>")
indexFile.WriteLine("                            <th style=""width: 20%;"">Email</th>")
indexFile.WriteLine("                            <th style=""width: 15%;"">Số điện thoại</th>")
indexFile.WriteLine("                            <th style=""width: 12%;"">Role</th>")
indexFile.WriteLine("                            <th style=""width: 12%;"">Trạng thái</th>")
indexFile.WriteLine("                            <th style=""width: 11%;"">Hành động</th>")
indexFile.WriteLine("                        </tr>")
indexFile.WriteLine("                    </thead>")
indexFile.WriteLine("                    <tbody>")
indexFile.WriteLine("                        @foreach (var user in Model)")
indexFile.WriteLine("                        {")
indexFile.WriteLine("                            <tr>")
indexFile.WriteLine("                                <td class=""fw-semibold"">#@user.UserId</td>")
indexFile.WriteLine("                                <td>@user.FullName</td>")
indexFile.WriteLine("                                <td class=""text-muted"">@user.Email</td>")
indexFile.WriteLine("                                <td>@user.PhoneNumber</td>")
indexFile.WriteLine("                                <td>")
indexFile.WriteLine("                                    <span class=""badge badge-pill""")
indexFile.WriteLine("                                          style=""@(user.Role == ""Admin"" ? ""background: rgba(139, 92, 246, 0.2); color: #d8b4fe;"" : user.Role == ""Staff"" ? ""background: rgba(56, 189, 248, 0.2); color: #7dd3fc;"" : ""background: rgba(34, 197, 94, 0.2); color: #86efac;"")"">")
indexFile.WriteLine("                                        @user.Role")
indexFile.WriteLine("                                    </span>")
indexFile.WriteLine("                                </td>")
indexFile.WriteLine("                                <td>")
indexFile.WriteLine("                                    <span class=""badge badge-status @(user.Status ? ""badge-active"" : ""badge-inactive"")"">")
indexFile.WriteLine("                                        @(user.Status ? ""Hoạt động"" : ""Bị khóa"")")
indexFile.WriteLine("                                    </span>")
indexFile.WriteLine("                                </td>")
indexFile.WriteLine("                                <td>")
indexFile.WriteLine("                                    <div class=""d-flex gap-2"">")
indexFile.WriteLine("                                        <a href=""/admin/users/edit/@user.UserId"" class=""btn btn-sm btn-primary rounded-pill"" title=""Chỉnh sửa"">")
indexFile.WriteLine("                                            <i class=""bi bi-pencil""></i>")
indexFile.WriteLine("                                        </a>")
indexFile.WriteLine("                                        <form action=""/admin/users/toggle-status/@user.UserId"" method=""post"" style=""display: inline;"">")
indexFile.WriteLine("                                            <button type=""submit"" class=""btn btn-sm @(user.Status ? ""btn-warning"" : ""btn-success"") rounded-pill"" title=""@(user.Status ? ""Khóa"" : ""Mở khóa"")"">")
indexFile.WriteLine("                                                <i class=""bi @(user.Status ? ""bi-lock"" : ""bi-unlock""></i>")
indexFile.WriteLine("                                            </button>")
indexFile.WriteLine("                                        </form>")
indexFile.WriteLine("                                        <form action=""/admin/users/delete/@user.UserId"" method=""post"" style=""display: inline;"" onclick=""return confirm('Bạn chắc chắn muốn xóa người dùng này?');"">")
indexFile.WriteLine("                                            <button type=""submit"" class=""btn btn-sm btn-danger rounded-pill"" title=""Xóa"">")
indexFile.WriteLine("                                                <i class=""bi bi-trash""></i>")
indexFile.WriteLine("                                            </button>")
indexFile.WriteLine("                                        </form>")
indexFile.WriteLine("                                    </div>")
indexFile.WriteLine("                                </td>")
indexFile.WriteLine("                            </tr>")
indexFile.WriteLine("                        }")
indexFile.WriteLine("                    </tbody>")
indexFile.WriteLine("                </table>")
indexFile.WriteLine("            </div>")
indexFile.WriteLine("        </div>")
indexFile.WriteLine("    }")
indexFile.WriteLine("</div>")
indexFile.Close()

WScript.Echo "Index.cshtml created successfully!"
