Dim fso, file, path
Set fso = CreateObject("Scripting.FileSystemObject")

path = "K:\Oishipan\OishipanMVC\Areas\Admin\Views\Users"

' Create Edit.cshtml
Set file = fso.CreateTextFile(path & "\Edit.cshtml", True, True)
file.WriteLine("@model OishipanAPI.DTOs.UpdateUserRequest")
file.WriteLine("")
file.WriteLine("@{")
file.WriteLine("    ViewData[""Title""] = ""Chỉnh sửa người dùng"";")
file.WriteLine("}")
file.WriteLine("")
file.WriteLine("<div class=""container-fluid"">")
file.WriteLine("    <div class=""d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4 gap-3"">")
file.WriteLine("        <div>")
file.WriteLine("            <h4 class=""fw-semibold"">Chỉnh sửa thông tin người dùng</h4>")
file.WriteLine("            <p class=""text-muted mb-0"">Cập nhật thông tin và quyền hạn.</p>")
file.WriteLine("        </div>")
file.WriteLine("        <a href=""/admin/users"" class=""btn btn-outline-secondary rounded-pill""><i class=""bi bi-arrow-left me-2""></i>Quay lại</a>")
file.WriteLine("    </div>")
file.WriteLine("")
file.WriteLine("    @if (!string.IsNullOrEmpty(ViewBag.Error))")
file.WriteLine("    {")
file.WriteLine("        <div class=""alert alert-danger alert-dismissible fade show"" role=""alert"">")
file.WriteLine("            <i class=""bi bi-exclamation-circle me-2""></i>@ViewBag.Error")
file.WriteLine("            <button type=""button"" class=""btn-close"" data-bs-dismiss=""alert""></button>")
file.WriteLine("        </div>")
file.WriteLine("    }")
file.WriteLine("")
file.WriteLine("    <div class=""row"">")
file.WriteLine("        <div class=""col-lg-8"">")
file.WriteLine("            <div class=""card admin-panel-card shadow-sm border-0 rounded-4 p-4"">")
file.WriteLine("                <form method=""post"" asp-action=""Edit"" asp-controller=""Users"" asp-area=""Admin"">")
file.WriteLine("                    <div class=""mb-4"">")
file.WriteLine("                        <div class=""alert alert-secondary rounded-3 py-2"">")
file.WriteLine("                            <strong>ID Người dùng:</strong> #@ViewBag.UserId")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""row mb-4"">")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Họ và tên <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <input type=""text"" class=""form-control form-control-dark rounded-pill"" name=""fullName"" asp-for=""FullName"" placeholder=""Nhập họ và tên"" required>")
file.WriteLine("                        </div>")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Email</label>")
file.WriteLine("                            <input type=""email"" class=""form-control form-control-dark rounded-pill"" asp-for=""Email"" readonly>")
file.WriteLine("                            <small class=""text-muted"">Email không thể thay đổi</small>")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""row mb-4"">")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Số điện thoại</label>")
file.WriteLine("                            <input type=""tel"" class=""form-control form-control-dark rounded-pill"" name=""phoneNumber"" asp-for=""PhoneNumber"" placeholder=""0xxxxxxxxx"" pattern=""^0\d{9}$"">")
file.WriteLine("                        </div>")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Role <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <select class=""form-select form-control-dark rounded-pill"" name=""role"" asp-for=""Role"" required>")
file.WriteLine("                                <option value=""Admin"">Admin</option>")
file.WriteLine("                                <option value=""Staff"">Staff</option>")
file.WriteLine("                                <option value=""User"">User</option>")
file.WriteLine("                            </select>")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""mb-4"">")
file.WriteLine("                        <label class=""form-label fw-semibold"">Địa chỉ</label>")
file.WriteLine("                        <input type=""text"" class=""form-control form-control-dark rounded-pill"" name=""address"" asp-for=""Address"" placeholder=""Nhập địa chỉ"">")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""mb-4"">")
file.WriteLine("                        <div class=""form-check form-switch"">")
file.WriteLine("                            <input class=""form-check-input"" type=""checkbox"" name=""status"" asp-for=""Status"" id=""statusCheck"">")
file.WriteLine("                            <label class=""form-check-label"" for=""statusCheck"" style=""cursor: pointer;"">")
file.WriteLine("                                Kích hoạt tài khoản (Nếu không chọn, tài khoản sẽ bị khóa)")
file.WriteLine("                            </label>")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""d-flex gap-3 justify-content-between"">")
file.WriteLine("                        <a href=""/admin/users"" class=""btn btn-outline-secondary rounded-pill px-4"">Hủy</a>")
file.WriteLine("                        <button type=""submit"" class=""btn btn-primary rounded-pill px-4"">")
file.WriteLine("                            <i class=""bi bi-check-circle me-2""></i>Cập nhật")
file.WriteLine("                        </button>")
file.WriteLine("                    </div>")
file.WriteLine("                </form>")
file.WriteLine("            </div>")
file.WriteLine("        </div>")
file.WriteLine("    </div>")
file.WriteLine("</div>")
file.Close()

WScript.Echo "Edit.cshtml created successfully!"
