Dim fso, file, path
Set fso = CreateObject("Scripting.FileSystemObject")

path = "K:\Oishipan\OishipanMVC\Areas\Admin\Views\Users"

' Create Create.cshtml
Set file = fso.CreateTextFile(path & "\Create.cshtml", True, True)
file.WriteLine("@model OishipanAPI.DTOs.CreateUserRequest")
file.WriteLine("")
file.WriteLine("@{")
file.WriteLine("    ViewData[""Title""] = ""Thêm người dùng mới"";")
file.WriteLine("}")
file.WriteLine("")
file.WriteLine("<div class=""container-fluid"">")
file.WriteLine("    <div class=""d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4 gap-3"">")
file.WriteLine("        <div>")
file.WriteLine("            <h4 class=""fw-semibold"">Thêm người dùng mới</h4>")
file.WriteLine("            <p class=""text-muted mb-0"">Tạo tài khoản mới với thông tin cơ bản.</p>")
file.WriteLine("        </div>")
file.WriteLine("        <a href=""/admin/users"" class=""btn btn-outline-secondary rounded-pill""><i class=""bi bi-arrow-left me-2""></i>Quay lại</a>")
file.WriteLine("    </div>")
file.WriteLine("")
file.WriteLine("    @if (!string.IsNullOrEmpty(ViewBag.Error))")
file.WriteLine("    {")
file.WriteLine("        <div class=""alert alert-danger alert-dismissible fade show"" role=""alert"">")
file.WriteLine("            <i class=""bi bi-exclamation-circle me-2""></i>@ViewBag.Error")
file.WriteLine("            <button type=""button"" class=""btn-close"" data-bs-dismiss=""alert""></button>")
file.WriteLine("        </div>")
file.WriteLine("    }")
file.WriteLine("")
file.WriteLine("    <div class=""row"">")
file.WriteLine("        <div class=""col-lg-8"">")
file.WriteLine("            <div class=""card admin-panel-card shadow-sm border-0 rounded-4 p-4"">")
file.WriteLine("                <form method=""post"" asp-action=""Create"" asp-controller=""Users"" asp-area=""Admin"">")
file.WriteLine("                    <div class=""row mb-4"">")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Họ và tên <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <input type=""text"" class=""form-control form-control-dark rounded-pill"" name=""fullName"" placeholder=""Nhập họ và tên"" required>")
file.WriteLine("                        </div>")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Email <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <input type=""email"" class=""form-control form-control-dark rounded-pill"" name=""email"" placeholder=""Nhập email"" required>")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""row mb-4"">")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Số điện thoại <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <input type=""tel"" class=""form-control form-control-dark rounded-pill"" name=""phoneNumber"" placeholder=""0xxxxxxxxx"" pattern=""^0\d{9}$"" required>")
file.WriteLine("                            <small class=""text-muted"">Định dạng: 0xxxxxxxxx (10 chữ số)</small>")
file.WriteLine("                        </div>")
file.WriteLine("                        <div class=""col-md-6"">")
file.WriteLine("                            <label class=""form-label fw-semibold"">Role <span class=""text-danger"">*</span></label>")
file.WriteLine("                            <select class=""form-select form-control-dark rounded-pill"" name=""role"" required>")
file.WriteLine("                                <option value="""">-- Chọn role --</option>")
file.WriteLine("                                <option value=""User"">User (Khách hàng)</option>")
file.WriteLine("                                <option value=""Staff"">Staff (Nhân viên)</option>")
file.WriteLine("                                <option value=""Admin"">Admin (Quản trị viên)</option>")
file.WriteLine("                            </select>")
file.WriteLine("                        </div>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""mb-4"">")
file.WriteLine("                        <label class=""form-label fw-semibold"">Mật khẩu <span class=""text-danger"">*</span></label>")
file.WriteLine("                        <input type=""password"" class=""form-control form-control-dark rounded-pill"" name=""password"" placeholder=""Nhập mật khẩu (tối thiểu 6 ký tự)"" minlength=""6"" required>")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""mb-4"">")
file.WriteLine("                        <label class=""form-label fw-semibold"">Địa chỉ</label>")
file.WriteLine("                        <input type=""text"" class=""form-control form-control-dark rounded-pill"" name=""address"" placeholder=""Nhập địa chỉ"">")
file.WriteLine("                    </div>")
file.WriteLine("")
file.WriteLine("                    <div class=""d-flex gap-3 justify-content-between"">")
file.WriteLine("                        <a href=""/admin/users"" class=""btn btn-outline-secondary rounded-pill px-4"">Hủy</a>")
file.WriteLine("                        <button type=""submit"" class=""btn btn-success rounded-pill px-4"">")
file.WriteLine("                            <i class=""bi bi-check-circle me-2""></i>Tạo người dùng")
file.WriteLine("                        </button>")
file.WriteLine("                    </div>")
file.WriteLine("                </form>")
file.WriteLine("            </div>")
file.WriteLine("        </div>")
file.WriteLine("    </div>")
file.WriteLine("</div>")
file.Close()

WScript.Echo "Create.cshtml created successfully!"
